[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
lib_deps =
  adafruit/DHT sensor library@^1.4.6
build_src_filter = +<*> -<secrets.example.h>

[env:ci]
extends = env:nodemcuv2
build_flags =
  -DWIFI_SSID=\"ci\"
  -DWIFI_PASSWORD=\"ci\"
  -DPUSHINGBOX_DEVID=\"ci\"
